package com.workee.api.domain.exception

enum class ErrorCode {
    INVALID_TOKEN,
    INTERNAL_SERVER_ERROR,
    ACCESS_DENIED,
    RESOURCE_NOT_ACCESSIBLE,
    UNAUTHORIZED_USER,
    BAD_REQUEST,
    USER_NOT_FOUND,
    DATABASE_UNAVAILABLE,
    KEYCLOAK_ERROR,
    USERNAME_OR_EMAIL_ALREADY_EXISTS,
    MANAGER_ALREADY_EXISTS,
    SMTP_EXCEPTION,
    EMAIL_VERIFICATION_NOT_FOUND,
    EMAIL_NOT_VERIFIED,
    REFRESH_TOKEN_NOT_FOUND
}