package com.workee.api.domain.exception

enum class ErrorCode {
    INVALID_TOKEN,
    INTERNAL_SERVER_ERROR,
    ACCESS_DENIED,
    RESOURCE_NOT_ACCESSIBLE,
    UNAUTHORIZED_USER,
    BAD_REQUEST,
    USER_NOT_FOUND,
    DATABASE_UNAVAILABLE
}